# Generated by Django 4.1.7 on 2023-04-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
