# Generated by Django 4.1.7 on 2023-03-22 16:34

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='task',
            field=auto_prefetch.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='board',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_tasks', to='task.taskboard'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('completed', 'Completed')], max_length=50),
        ),
    ]
