# Generated by Django 4.1.7 on 2023-03-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_comments_taskcomments_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
