# Generated by Django 4.1.7 on 2023-03-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_delete_taskstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskComments',
            new_name='TaskComment',
        ),
    ]
