# Generated by Django 4.1.7 on 2023-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_taskcomments_taskcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpriority',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['name', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='taskpriority',
            name='number',
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='level',
            field=models.PositiveIntegerField(),
        ),
    ]
