# Generated by Django 4.1.7 on 2023-03-24 07:45

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('task', '0005_alter_taskpriority_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpriority',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name_plural': 'Task Priorities'},
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=auto_prefetch.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='team.team'),
            preserve_default=False,
        ),
    ]
