# Generated by Django 4.1.7 on 2023-04-04 22:10

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_teammembers_teammember'),
        ('task', '0006_alter_taskpriority_options_task_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=auto_prefetch.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_tasks', to='task.taskboard'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=auto_prefetch.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_tasks', to='task.taskcategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=auto_prefetch.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='team.team'),
        ),
    ]
